Make loading state name more generic
infinum/ngx-nuts-and-bolts pull request #17
Opened 2022-01-19 11:34 UTC by Erbenos

Addresses #16.

2022-01-27 11:34 UTC, fvoska approved these changes

2022-01-27 14:44 UTC, JosipJanus requested changes
Before merging please move this readme.md into docusaurus docs folder. You already have placeholder for this file.

2022-02-02 18:46 UTC, Erbenos commented
We will perhaps need to better figure out how to structure the docs and what naming convention to follow there as now its was unclear, at least to me that is.

2022-02-04 11:39 UTC, fvoska approved these changes

2022-02-04 11:39 UTC, merged