Add inview directive
infinum/ngx-nuts-and-bolts pull request #27
Opened 2022-01-19 15:42 UTC by Erbenos

Addresses #25.

2022-01-27 12:53 UTC, fvoska requested changes

2022-01-27 12:53 UTC, fvoska commented on libs/ngx-nuts-and-bolts/src/lib/directives/in-view/README.md
> +Often times, one may be interested to know whether or not piece of DOM is visible on user's screen. There is [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_
```suggestion
Often times, one may be interested to know whether or not a piece of DOM is visible on the user's screen. We utilize [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) just for that purpose and this directive is a very simple option-less wrapper around it.
```

2022-02-02 17:42 UTC, Erbenos commented on libs/ngx-nuts-and-bolts/src/lib/directives/in-view/README.md
> +	template: `<div infInView (inView)="inView$.next($event)>{{ inView$ | async }}</div>`,
cb2a052

2022-02-02 17:45 UTC, Erbenos commented on libs/ngx-nuts-and-bolts/src/lib/directives/in-view/README.md
> +	template: `<div infInView (inView)="inView$.next($event)>{{ inView$ | async }}</div>`,
f33a7b5

2022-02-02 17:45 UTC, Erbenos commented on libs/ngx-nuts-and-bolts/src/lib/directives/in-view/README.md
> +Often times, one may be interested to know whether or not piece of DOM is visible on user's screen. There is [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_
f33a7b5

2022-02-02 17:45 UTC, Erbenos commented on libs/ngx-nuts-and-bolts/src/lib/directives/in-view/README.md
> +`infInView` directive allows you to determine if a piece of DOM is visible on user's screen.
f33a7b5

2022-02-04 11:41 UTC, fvoska approved these changes

2022-02-21 09:16 UTC, merged