Issue 23 add fade height animations
infinum/ngx-nuts-and-bolts pull request #30
Opened 2022-01-20 12:24 UTC by JosipJanus

2022-01-20 12:45 UTC, Erbenos commented on libs/ngx-nuts-and-bolts/src/lib/animations/height-fade-animation-component.stories.ts
> +	public isOpened = false;
Would be nice if this was controllable with a knob.

2022-01-26 10:32 UTC, fvoska requested changes

2022-01-26 10:32 UTC, fvoska commented on libs/ngx-nuts-and-bolts/src/lib/animations/README.md
> +This library includes two more commonly used animations (`fadeAnimation()` and `heightAnimation()`). For usage and general information about angular animations please consider visiting official [Angu
```suggestion
This library includes two commonly used animations — (`fadeAnimation()` and `heightAnimation()`). For usage and general information about Angular animations, please consider visiting the official [Angular animations documentation](https://angular.io/guide/animations)
```

2022-01-28 09:26 UTC, fvoska approved these changes

2022-01-31 08:46 UTC, merged