Add infObserveResize directive
infinum/ngx-nuts-and-bolts pull request #60
Opened 2022-03-01 18:54 UTC by Erbenos

# Description

Abstracts ResizeObserver into primitive directive.

Tests simple interaction that replaces underlying ResizeObserver with mocks as Jest does not support ResizeObserver and testing a polyfill would negate the point of it anyway.

Documentation includes notes on how to test events fired from the directive if need be.

## Type of change

Please delete options that are not relevant.

- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ X ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [ X ] I have made corresponding changes to the documentation
- [ X ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (Jest doesn't support ResizeObserver)
- [ X ] New and existing unit tests pass locally with my changes

2022-03-04 21:18 UTC, Erbenos commented
TODO myself: add directive to exports

2022-03-16 14:00 UTC, JosipJanus requested changes

2022-03-24 19:39 UTC, Erbenos commented on ngx-nuts-and-bolts-docs/docs/directives/observe-resize.md
> +Clearly the browser doesn't fire ResizeObserver notifications the instant one of the elements gets resized or to make it clearer, it doesn't trigger the moment anything which could cause a resize hap
It attempts to explain when exactly ResizeObserver notification is fired so I can't use that exact thing in the explanation itself, that would be 'recursive'.

I tried to reword the paragraph a little bit.

2022-03-24 19:40 UTC, Erbenos commented on libs/ngx-nuts-and-bolts/src/lib/directives/observe-resize/observe-resize.stories.ts
> +		<button (click)="toggleContent()">Toggle content</button>
[90d0b12](https://github.com/infinum/ngx-nuts-and-bolts/pull/60/commits/90d0b1286244dfab22cd27e453b050fc27bb2f2f)

2022-03-24 19:40 UTC, Erbenos commented on libs/ngx-nuts-and-bolts/src/lib/directives/observe-resize/observe-resize.stories.ts
> +		<button (click)="appendText()">Append text</button>
[90d0b12](https://github.com/infinum/ngx-nuts-and-bolts/pull/60/commits/90d0b1286244dfab22cd27e453b050fc27bb2f2f)

2022-03-24 19:40 UTC, Erbenos commented on ngx-nuts-and-bolts-docs/docs/directives/observe-resize.md
> +Clearly the browser doesn't fire ResizeObserver notifications the instant one of the elements gets resized or to make it clearer, it doesn't trigger the moment anything which could cause a resize hap
[90d0b12](https://github.com/infinum/ngx-nuts-and-bolts/pull/60/commits/90d0b1286244dfab22cd27e453b050fc27bb2f2f)

2022-03-24 19:40 UTC, Erbenos commented
Thanks for review so far.

2024-01-17 14:40 UTC, fvoska commented
Abandoning in favour of https://taiga-family.github.io/ng-web-apis/resize-observer

2024-01-17 14:40 UTC, closed without merging